# Open markdown links with mdcat instead of $EDITOR, as an overlay on top
protocol file
ext md
action launch --type=overlay --cwd=current -- mdcat --paginate -- ${FILE_PATH}

# 
protocol file
mime text/*
action launch --type=tab $EDITOR ${FILE_PATH}
